### ISSUE TITLE
Regex rules for copyright check

### ISSUE THREAD

**Issue by kmc-spyro** [Spyro-Soft/scargo#405]
**Is your feature request related to a problem? Please describe.**
Required copyright statement format is fixed and not flexible. It requires to use standard c++ comments '//'.
And here we have a few problems:
- this could not work for other types of files, e.g. pure C
- doxygen cannot be used for copyrigth statement (`@copyrigth`)
- the lines of the statement cannot be flexible - for instance contain different year depending when the file was created

**Describe the solution you'd like**
Besides current approach also allow to use regex statement description in scargo.toml file, e.g.,:
```toml
[check.copyright]
description = '''
/\*\*
 \* @copyright Copyright \(C\) \d* SpyroSoft Solutions. All rights reserved.
 \*'''
exclude = []
```
and this would fit for instance this doxygen comment:
```cpp
/**
 * @copyright Copyright (C) 2023 SpyroSoft Solutions. All rights reserved.
 */
```
