### ISSUE TITLE
`[tests]` section in config does not support additional variables

### ISSUE THREAD

**Issue by rkapuscik** [Spyro-Soft/scargo#50]
When configuring the project with `scargo.toml`, it's possible to define additional variables that are translated to CMake variables in the `[profile.*]` sections:
```toml
[profile.Release]        
cflags   = "-O3 -DNDEBUG"
cxxflags = "-O3 -DNDEBUG"
bootloader_version = "0.0.1"
```
It is not possible to do this in the same way for the `[tests]`.
